import { Provider } from "@/src/types/core";
import { PROVIDER_LOGOS } from "@/src/constants/logos";
export const PREDEFINED_PROVIDERS = {
  anthropic: {
    name: "Anthropic",
    endpoint: "https://api.anthropic.com",
    source: "anthropic" as const,
    capabilities: {
      llm: true,
      tts: false,
      stt: false,
    },
    logo: "https://www.anthropic.com/images/icons/favicon-32x32.png",
    keyRequired: true,
    signupUrl: "https://console.anthropic.com/",
  } as Provider,
  openai: {
    name: "OpenAI",
    endpoint: "https://api.openai.com",
    source: "openai" as const,
    capabilities: {
      llm: true,
      tts: false,
      stt: false,
      image: true,
      embedding: true,
    },
    logo: "https://openai.com/icon.svg",
    keyRequired: true,
    signupUrl: "https://platform.openai.com/signup",
  } as Provider,
  ollama: {
    name: "Ollama",
    endpoint: "http://localhost:11434",
    source: "ollama" as const,
    capabilities: {
      llm: true,
      tts: false,
      stt: false,
      embedding: true,
    },
    logo: PROVIDER_LOGOS.ollama,
    keyRequired: false,
  } as Provider,
  elevenlabs: {
    name: "ElevenLabs",
    endpoint: "https://api.elevenlabs.io/v1/text-to-speech",
    source: "elevenlabs" as const,
    capabilities: {
      llm: false,
      tts: true,
      stt: false,
    },
    logo: "https://elevenlabs.io/icon.svg",
    keyRequired: true,
    signupUrl: "https://elevenlabs.io/sign-up",
  } as Provider,
  searxng: {
    name: "SearXNG",
    endpoint: "https://baresearch.org",
    source: "searxng" as const,
    capabilities: {
      llm: false,
      tts: false,
      stt: false,
      search: true,
    },
    logo: "https://searx.bndkt.io/static/themes/simple/img/favicon.svg",
    keyRequired: false,
  } as Provider,
  replicate: {
    name: "Replicate",
    endpoint: "https://api.replicate.com",
    source: "replicate" as const,
    capabilities: {
      llm: false,
      tts: false,
      stt: false,
      image: true,
    },
    logo: "https://replicate.com/assets/favicon-dark-mode.png",
    keyRequired: true,
    signupUrl: "https://replicate.com/signin",
  } as Provider,
  cerebras: {
    name: "Cerebras",
    endpoint: "https://api.cerebras.ai",
    source: "cerebras" as const,
    capabilities: {
      llm: true,
      tts: false,
      stt: false,
    },
    logo: "https://inference.cerebras.ai/images/logo/cb-fav-144.png",
    keyRequired: true,
    signupUrl: "https://inference.cerebras.ai/",
  } as Provider,
} as const;
